import type { Metadata } from 'next';
import './globals.css';
import { Open_Sans, Playfair_Display_SC } from 'next/font/google';
import Navigation from '@/components/navigation/navigation';

const openSansLight = Open_Sans({
  variable: '--font-open-sans-light',
  subsets: ['latin'], 
});

const playfairDisplaySc = Playfair_Display_SC({
  variable: '--font-playfair-display-sc',
  subsets: ['latin'],
  weight: ['400', '700', '900'],
  style: ['normal', 'italic'],
});

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${openSansLight.variable} ${playfairDisplaySc.variable}`}>
      <body className={'antialiased'}>
        <Navigation />
        {children}
      </body>
    </html>
  );
}
